# Generated by Django 4.2.7 on 2023-11-23 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0006_enquiry"),
    ]

    operations = [
        migrations.CreateModel(
            name="GalleryImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("alt_text", models.CharField(max_length=150)),
                ("img", models.ImageField(null=True, upload_to="gallery_imgs/")),
            ],
        ),
    ]
