# Generated by Django 4.2.7 on 2023-11-24 14:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0009_galleryimage_gallery"),
    ]

    operations = [
        migrations.CreateModel(
            name="SubPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=150)),
                ("price", models.IntegerField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="SubPlanFeatures",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=150)),
                (
                    "subplan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="main.subplan"
                    ),
                ),
            ],
        ),
    ]
