# Generated by Django 4.2.7 on 2023-11-24 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0010_subplan_subplanfeatures"),
    ]

    operations = [
        migrations.AddField(
            model_name="subplan",
            name="highlight_status",
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name="subplan", name="price", field=models.IntegerField(),
        ),
    ]
